inherit_from:
  - .rubocop_airbnb.yml
  - .rubocop_overrides.yml

AllCops:
  CacheRootDirectory: tmp/rubocop
  TargetRubyVersion: 2.5
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
