shared: &shared
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  encoding: unicode
  reconnect: true
  connect_timeout: 1
  pool: <%= ENV['MAX_THREADS'] || 5 %>

development:
  <<: *shared
  url: postgres://postgres:R0tate1@pg/
  database: bp-we-eat_dev

test:
  <<: *shared
  url: postgres://postgres:R0tate1@pg/
  database: bp-we-eat_test

staging:
  <<: *shared

production:
  <<: *shared
